# correct password
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "liltim",
  "password": "1234"
}

###
# wrong password
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "liltim",
  "password": "12345"
}



###
POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "bobbyboy",
  "password": "1234"
}

###

GET http://localhost:8080/api/getUser
###

GET http://localhost:8080/api/signout